name: Build AppImage

# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install libfuse2
        run: |
          sudo apt update
          sudo apt install -y libfuse2
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies from setup.py
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Prepare AppDir and AppRun
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/lib/python3.8/site-packages
          cp -r $(python -c 'import site; print(site.getsitepackages()[0])')/* AppDir/usr/lib/python3.8/site-packages/
          cp -r molcompview AppDir/usr/bin/
          echo '#!/bin/bash' > AppDir/AppRun
          echo 'HERE=$(dirname $(readlink -f "${0}"))' >> AppDir/AppRun
          echo 'export PYTHONPATH=${HERE}/usr/lib/python3.8/site-packages' >> AppDir/AppRun
          echo 'exec python3 ${HERE}/usr/bin/molcompview/main.py "$@"' >> AppDir/AppRun
          chmod +x AppDir/AppRun

      - name: Download linuxdeploy and Create AppImage
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage

      - name: Upload AppImage as Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: molcomplib.AppImage
          path: molcomplib.AppImage


